Adiciona action com pipeline de deploy
produtoreativo/adora pull request #24
Opened 2022-09-13 00:53 UTC by ViniciusSantosFS

2022-09-13 18:55 UTC, cmilfont requested changes

2022-09-13 18:55 UTC, cmilfont commented on ormconfig.ts
> +import * as dotenv from 'dotenv';
Precisou importar diretamente o env?
Não resolveu com o módulo de config?
https://docs.nestjs.com/techniques/configuration

2022-09-16 20:52 UTC, ViniciusSantosFS commented on ormconfig.ts
> +import * as dotenv from 'dotenv';
@crgmzlps Realizou modificações @cmilfont

2022-10-01 13:30 UTC, cmilfont approved these changes

2022-10-01 13:30 UTC, merged